language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - OLD_PHP_VERSION="7.2"
    - XDEBUG_MODE="coverage"
  matrix:
    - DEPENDENCIES="beta"
    - DEPENDENCIES="low"
    - DEPENDENCIES="stable"

matrix:
  fast_finish: true
  allow_failures:
    - env: DEPENDENCIES="beta"
    - env: DEPENDENCIES="low"
    - env: SYMFONY_VERSION="dev-master"


before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [ -n "$GH_TOKEN" ]; then
      composer config github-oauth.github.com ${GH_TOKEN};
    fi;
  - mkdir -p build/logs
  - |
    version() {
      echo "$@" | gawk -F. '{ printf("%03d%03d%03d\n", $1,$2,$3); }';
    }
    export -f version

install:
  - if [ "$(version "$(phpenv version-name)")" -lt "$(version "$OLD_PHP_VERSION")" ]; then
      composer remove friendsofphp/php-cs-fixer phpstan/phpstan phpstan/phpstan-phpunit phpunit/phpunit --dev;
      composer require phpunit/phpunit "5.7.*" --dev;
    fi
  - if [ "$DEPENDENCIES" = "beta" ]; then
      composer config minimum-stability beta;
      composer update -n --prefer-dist;
    elif [ "$DEPENDENCIES" = "low" ]; then
      composer update -n --prefer-dist --prefer-lowest;
    else
      composer update -n --prefer-dist;
    fi;

script:
  - if [ "$(version "$(phpenv version-name)")" -lt "$(version "$OLD_PHP_VERSION")" ]; then
      echo "File validation is skipped for older PHP versions";
    else
      composer validate-files;
    fi;
  - if [ "$(version "$(phpenv version-name)")" -lt "$(version "$OLD_PHP_VERSION")" ]; then
      echo "Static analysis is skipped for older PHP versions";
    else
      composer run-static-analysis-including-tests;
    fi;
  - if [ "$(version "$(phpenv version-name)")" -lt "$(version "$OLD_PHP_VERSION")" ]; then
      echo "Code style check is skipped for older PHP versions";
    else
      composer check-code-style;
    fi;
  - if [ "$(version "$(phpenv version-name)")" -lt "$(version "$OLD_PHP_VERSION")" ]; then
      echo "Security check is skipped for older PHP versions";
    else
      composer check-security;
    fi;
  - composer run-tests-with-clover

after_script:
  - if [ "$(version "$(phpenv version-name)")" -lt "$(version "$OLD_PHP_VERSION")" ]; then
      echo "Coveralls report is skipped for older PHP versions";
    else
      bin/php-coveralls -v;
    fi;
