language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: nightly

env:
  global:
    - deps=no

before_install:
  - composer self-update

install:
  - composer install

script:
  - composer validate-files
  - composer code-style
